# Generated by Django 4.1.1 on 2022-10-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickFlips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_list', models.CharField(max_length=100)),
                ('profit', models.IntegerField()),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.item')),
            ],
        ),
    ]
