# Generated by Django 4.1.1 on 2022-10-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_item_quickflips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='quickflips',
            old_name='ingredient_list',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='quickflips',
            name='parent_item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.quickflips'),
        ),
    ]
